In [37]:
#problem_1
import numpy as np

my_2d_array = np.random.random((10, 3))
print(my_2d_array)
index = np.argmin(abs(my_2d_array - 0.5),axis=1)
for i in range(10):
   print(my_2d_array[i,index[i]])


[[0.80820928 0.95106029 0.50202185]
 [0.9023729  0.38895043 0.84280721]
 [0.21430011 0.06778843 0.43478298]
 [0.80019992 0.25713685 0.10640643]
 [0.26771225 0.53862767 0.10278895]
 [0.94478867 0.34837344 0.72496837]
 [0.59123372 0.73613568 0.51344517]
 [0.06532343 0.78703783 0.68444918]
 [0.15917546 0.50338855 0.13706865]
 [0.29426213 0.40940296 0.016559  ]]
0.5020218509542242
0.3889504349753645
0.43478297712266056
0.2571368513411776
0.5386276663244859
0.3483734430784432
0.513445172200594
0.6844491784994299
0.5033885491144896
0.40940295621186096


In [51]:
#problem_2
import numpy as np

a = np.random.random((6, 6))
print(a)
print(np.sum(a, axis = 1) / np.min(a, axis = 0))

[[0.20161452 0.53107709 0.52047001 0.32590301 0.55186394 0.3820743 ]
 [0.05503518 0.51022634 0.23221184 0.36570961 0.716518   0.00186385]
 [0.28899834 0.03632261 0.44599346 0.84369662 0.75035688 0.69452199]
 [0.15974288 0.07198967 0.94659536 0.44436789 0.87089756 0.55652858]
 [0.39275005 0.03764551 0.34166348 0.78420579 0.70468323 0.97619902]
 [0.80394288 0.1799415  0.68324485 0.28215622 0.0026994  0.66897121]]
[  45.66175401   51.80147391   13.17714857   10.81004674 1199.21010296
 1406.20490167]


In [5]:
#problem_3
import numpy as np

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) 
new_x = x[0:-1:1]
print(np.max(new_x[np.argwhere(new_x == 0) + 1]))

5


In [6]:
#problem_4
import numpy as np

x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
np.add.at(x, i, 1)
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [32]:
#problem_5
import numpy as np

a = np.arange(16).reshape(4, 4)
print(a)
d = dict()
for i in range(7):
    diag = []
    print(i)
    for j in range(max(i-3,0),min(i,3)+1):
        diag.append(a[j,i-j])
        d.update({i:diag})
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
0
1
2
3
4
5
6
{0: [0], 1: [1, 4], 2: [2, 5, 8], 3: [3, 6, 9, 12], 4: [7, 10, 13], 5: [11, 14], 6: [15]}
